export const SERVICE_CONFIG = Symbol("SERVICE_CONFIG");
export const TRANSACTION_REPOSITORY = Symbol("TRANSACTION_REPOSITORY");
export const TRANSACTION_CACHE = Symbol("TRANSACTION_CACHE");
export const PAYMENT_CLIENT = Symbol("PAYMENT_CLIENT");
export const TRANSACTION_EVENT_PUBLISHER = Symbol("TRANSACTION_EVENT_PUBLISHER");
